#!/usr/bin/env php
<?php

namespace Behavioral\ChainOfResponsibility;

require_once "./vendor/autoload.php";

$chain  = new NoticeHandler();

try {
    $chain->setNext(new WarningHandler())->setNext(new ErrorHandler());
    $chain->execute(NoticeHandler::class);
    $chain->execute(WarningHandler::class);
    $chain->execute(ErrorHandler::class);
} catch (\Exception $e) {
    printf("%s", "Caught exception: " . $e->getMessage() . "\n");
}
