#!/usr/bin/env php
<?php

namespace Behavioral\ChainOfResponsibility;

require_once 'vendor/autoload.php';

$chain = new Chain();
$chain->addToChain(NoticeHandler::class);
$chain->addToChain(WarningHandler::class);
$chain->addToChain(ErrorHandler::class);

$chain->run(ErrorHandler::class);
$chain->run(WarningHandler::class);
$chain->run(NoticeHandler::class);
