#!/usr/bin/env php
<?php

namespace Behavioral\ChainOfResponsibility;

require_once "./vendor/autoload.php";

// Create the starting element of the chain
$notice = new NoticeHandler();

try {
    // Add items to the chain.
    $notice->setNext(new WarningHandler())->setNext(new ErrorHandler());

    // Call the handler by name
    $notice->execute(NoticeHandler::class);
    $notice->execute(WarningHandler::class);
    $notice->execute(ErrorHandler::class);
} catch (\Exception $e) {
    printf("%s", "Caught exception: " . $e->getMessage() . "\n");
}
